
export const CATEGORIES = [
  'Window 11',
  'Tech',
  'iOS 18',
  'GTA 6',
  'Google Gemini',
  'Roblox',
  'AI',
  'Gaming',
  'Mobile',
  'Science',
  'Startups',
  'Cybersecurity',
  'Gadgets',
  'Software',
  'Hardware',
  'Apple',
  'Google',
  'Microsoft',
  'Electric Vehicles',
  'Space'
];

export type Article = {
  id: string;
  slug: string;
  title: string;
  category: string;
  imageId: string;
  author: string;
  date: string;
  tags: string[];
};

export const ARTICLES: Article[] = [
  {
    id: '1',
    slug: 'ergonomic-keyboards-the-future-of-typing',
    title: 'Ergonomic Keyboards: The Future of Typing Comfort',
    category: 'Keyboards',
    imageId: 'article_1',
    author: 'Jane Doe',
    date: 'Oct 5, 2023',
    tags: ['ergonomics', 'hardware', 'productivity'],
  },
  {
    id: '2',
    slug: 'custom-keyboards-a-deep-dive',
    title: 'A Deep Dive into the World of Custom Keyboards',
    category: 'Keyboards',
    imageId: 'article_2',
    author: 'John Smith',
    date: 'Oct 4, 2023',
    tags: ['diy', 'mechanical keyboards', 'hardware'],
  },
  {
    id: '3',
    slug: 'the-rise-of-60-percent-keyboards',
    title: 'The Rise of 60% Keyboards in Modern Setups',
    category: 'Keyboards',
    imageId: 'article_3',
    author: 'Emily White',
    date: 'Oct 3, 2023',
    tags: ['compact', 'mechanical keyboards', 'gear'],
  },
  {
    id: '4',
    slug: 'rgb-keyboards-do-they-improve-gaming',
    title: 'RGB Keyboards: Do They Really Improve Your Gaming?',
    category: 'Gaming',
    imageId: 'article_4',
    author: 'Michael Brown',
    date: 'Oct 2, 2023',
    tags: ['gaming', 'rgb', 'peripherals'],
  },
  {
    id: '5',
    slug: 'split-keyboards-for-better-productivity',
    title: 'How Split Keyboards Can Boost Your Productivity',
    category: 'Keyboards',
    imageId: 'article_5',
    author: 'Sarah Green',
    date: 'Oct 1, 2023',
    tags: ['productivity', 'ergonomics', 'office setup'],
  },
   {
    id: '6',
    slug: 'the-charm-of-vintage-keyboards',
    title: 'Exploring the Charm of Vintage Mechanical Keyboards',
    category: 'Keyboards',
    imageId: 'article_6',
    author: 'David Black',
    date: 'Sep 30, 2023',
    tags: ['retro', 'vintage tech', 'collecting'],
  },
  {
    id: '7',
    slug: 'a-look-at-the-newest-gaming-mice',
    title: 'A Look at the Newest Gaming Mice on the Market',
    category: 'Gaming',
    imageId: 'article_7',
    author: 'Chris Johnson',
    date: 'Oct 6, 2023',
    tags: ['gaming', 'mice', 'esports', 'hardware'],
  },
  {
    id: '8',
    slug: 'high-refresh-rate-monitors-are-they-worth-it',
    title: 'High Refresh Rate Monitors: Are They Worth It?',
    category: 'Monitors',
    imageId: 'article_8',
    author: 'Jessica Lee',
    date: 'Oct 7, 2023',
    tags: ['monitors', 'gaming', 'pc building'],
  },
  {
    id: '9',
    slug: 'the-best-budget-smartphones-of-the-year',
    title: 'The Best Budget Smartphones of the Year',
    category: 'Mobile',
    imageId: 'article_9',
    author: 'Kevin Martinez',
    date: 'Oct 8, 2023',
    tags: ['smartphones', 'budget tech', 'android', 'ios'],
  },
  {
    id: '10',
    slug: 'top-5-upcoming-rpgs',
    title: 'Top 5 Upcoming RPGs to Watch Out For',
    category: 'Gaming',
    imageId: 'article_1',
    author: 'Laura Chen',
    date: 'Oct 9, 2023',
    tags: ['gaming', 'rpg', 'upcoming games'],
  },
  {
    id: '11',
    slug: 'the-evolution-of-battle-royale-games',
    title: 'The Evolution of Battle Royale Games',
    category: 'Gaming',
    imageId: 'article_2',
    author: 'Mark Wilson',
    date: 'Oct 10, 2023',
    tags: ['gaming', 'battle royale', 'history'],
  },
  {
    id: '12',
    slug: 'how-to-build-your-own-gaming-pc',
    title: 'A Beginner\'s Guide to Building Your Own Gaming PC',
    category: 'Hardware',
    imageId: 'article_3',
    author: 'Olivia Davis',
    date: 'Oct 11, 2023',
    tags: ['pc building', 'diy', 'hardware', 'gaming'],
  },
  {
    id: '13',
    slug: 'the-most-anticipated-games-of-next-year',
    title: 'The Most Anticipated Games of Next Year',
    category: 'Gaming',
    imageId: 'article_4',
    author: 'Daniel Taylor',
    date: 'Oct 12, 2023',
    tags: ['gaming', 'e3', 'previews'],
  },
  {
    id: '14',
    slug: 'cloud-gaming-services-compared',
    title: 'Cloud Gaming Services: A Head-to-Head Comparison',
    category: 'Gaming',
    imageId: 'article_5',
    author: 'Sophia Anderson',
    date: 'Oct 13, 2023',
    tags: ['cloud gaming', 'geforce now', 'xcloud'],
  },
  {
    id: '15',
    slug: 'esports-from-niche-to-mainstream',
    title: 'The Rise of eSports: From Niche to Mainstream',
    category: 'Gaming',
    imageId: 'article_6',
    author: 'James Harris',
    date: 'Oct 14, 2023',
    tags: ['esports', 'gaming', 'community'],
  },
  {
    id: '16',
    slug: 'best-co-op-games-to-play-with-friends',
    title: 'Best Co-op Games to Play with Your Friends',
    category: 'Gaming',
    imageId: 'article_7',
    author: 'Chloe Lewis',
    date: 'Oct 15, 2023',
    tags: ['co-op', 'multiplayer', 'gaming'],
  },
  {
    id: '17',
    slug: 'ai-in-game-development',
    title: 'How AI is Revolutionizing Game Development',
    category: 'AI',
    imageId: 'article_8',
    author: 'Ben Carter',
    date: 'Oct 16, 2023',
    tags: ['ai', 'game dev', 'innovation'],
  },
  {
    id: '18',
    slug: 'next-gen-consoles-one-year-later',
    title: 'Next-Gen Consoles: One Year Later',
    category: 'Gaming',
    imageId: 'article_9',
    author: 'Ethan Scott',
    date: 'Oct 17, 2023',
    tags: ['ps5', 'xbox series x', 'consoles'],
  },
  {
    id: '19',
    slug: 'the-future-of-vr-gaming',
    title: 'What\'s Next for Virtual Reality Gaming?',
    category: 'Gaming',
    imageId: 'article_1',
    author: 'Mia Rodriguez',
    date: 'Oct 18, 2023',
    tags: ['vr', 'virtual reality', 'future tech'],
  },
  {
    id: '20',
    slug: 'understanding-geforce-rtx-4090',
    title: 'Nvidia\'s GeForce RTX 4090: A Beast Unleashed',
    category: 'Hardware',
    imageId: 'article_2',
    author: 'Lucas Evans',
    date: 'Oct 19, 2023',
    tags: ['gpu', 'nvidia', 'pc hardware'],
  }
];

export const TRENDING_ARTICLES = ARTICLES.slice(0, 4);

export const BAROMETER_DATA = [
  { topic: 'AI', heat: 95 },
  { topic: 'EVs', heat: 85 },
  { topic: 'Gaming', heat: 80 },
  { topic: 'Apple', heat: 70 },
  { topic: 'Startups', heat: 60 },
  { topic: 'Cybersecurity', heat: 75 },
  { topic: 'Gadgets', heat: 65 },
  { topic: 'Software', heat: 88 },
];
